import type { Game, LeaderboardEntry } from '@/types/game';

export const featuredGames: Game[] = [
  {
    id: 'g0',
    title: 'Candy Crush',
    genre: 'Puzzle',
    coverUrl: '/assets/games/candy-crush.png',
    rating: 4.7,
    likes: 41_300,
    coverAspectRatio: 0.32,
    showInfo: false,
  },
  {
    id: 'g1',
    title: 'Islanders: New Shores',
    genre: 'Simulation',
    coverUrl: '/assets/games/islanders.png',
    rating: 4.9,
    likes: 54_200,
    coverAspectRatio: 0.89,
  },
  {
    id: 'g2',
    title: 'Vacation Cafe Simulator',
    genre: 'Simulation',
    coverUrl: '/assets/games/vacation-cafe.png',
    rating: 4.8,
    likes: 28_700,
    coverAspectRatio: 2.125,
    featured: true,
  },
  {
    id: 'g3',
    title: 'Winter Burrow',
    genre: 'Adventure',
    coverUrl: '/assets/games/winter-burrow.png',
    rating: 4.9,
    likes: 32_400,
    coverAspectRatio: 0.89,
  },
  {
    id: 'g4',
    title: 'Bubble Shooter',
    genre: 'Arcade',
    coverUrl: '/assets/games/bubble-shooter.png',
    rating: 4.7,
    likes: 23_600,
    coverAspectRatio: 0.32,
    showInfo: false,
  },
];

export const leaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    playerName: 'Alex_Pro99',
    avatarInitials: 'AP',
    avatarColor: '#F5B942',
    gamesPlayed: 142,
    totalScore: 94_250,
    streakDays: 12,
    favoriteGame: 'Heartopia',
  },
  {
    rank: 2,
    playerName: 'CozyGamer_x',
    avatarInitials: 'CG',
    avatarColor: '#8FDDB0',
    gamesPlayed: 118,
    totalScore: 81_400,
    streakDays: 8,
    favoriteGame: 'Cat Mail Co.',
  },
  {
    rank: 3,
    playerName: 'MatchMaster',
    avatarInitials: 'MM',
    avatarColor: '#8FC6F0',
    gamesPlayed: 98,
    totalScore: 72_110,
    streakDays: 5,
    favoriteGame: 'Tiny Glade',
  },
  {
    rank: 4,
    playerName: 'BubblePop',
    avatarInitials: 'BP',
    avatarColor: '#F0A8DC',
    gamesPlayed: 87,
    totalScore: 65_900,
    streakDays: 3,
    favoriteGame: 'Whisper of the House',
  },
  {
    rank: 5,
    playerName: 'SudokuGod',
    avatarInitials: 'SG',
    avatarColor: '#C3B4F0',
    gamesPlayed: 74,
    totalScore: 59_320,
    streakDays: 2,
    favoriteGame: 'Cat Chess',
  },
];
